services:
  db:
    image: postgres:15-alpine
    container_name: postgres_scleenkr
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: scleenkr_api
    ports:
      - "3000:3000"
    environment:
      DB_HOST: ${DB_HOST} 
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD} 
      DB_PORT: ${DB_PORT}
      PGSSLMODE: disable #Trava de segurança para o banco do docker com SSL desabilitado
    depends_on:
      - db

volumes:
  pgdata: